Formated

diff --git a/Jenkinsfile_CI_Ops_Repo b/Jenkinsfile_CI_Ops_Repo
--- a/Jenkinsfile_CI_Ops_Repo
+++ b/Jenkinsfile_CI_Ops_Repo
@@ -1,171 +1,183 @@
 pipeline {
-    
-    agent any
-    
-    triggers {
-       githubPush()
-     }
 
-    options {
-      buildDiscarder logRotator(numToKeepStr: '5')
-      timeout(time: 10, unit: 'MINUTES')
-      disableConcurrentBuilds()
+  agent any
+
+  triggers {
+    githubPush()
+  }
+
+  options {
+    buildDiscarder logRotator(numToKeepStr: '5')
+    timeout(time: 10, unit: 'MINUTES')
+    disableConcurrentBuilds()
+  }
+
+  environment {
+    AWS_REGION = "ap-south-1"
+    EKS_CLUSTER_NAME = "eks-demo"
+    IMAGE_REGISTRY_ENDPOINT = "775694652978.dkr.ecr.ap-south-1.amazonaws.com"
+    IMAGE_REPOSITORY_NAME = "student-reg-webapp"
+    IMAGE_REGISTRY = "${IMAGE_REGISTRY_ENDPOINT}/${IMAGE_REPOSITORY_NAME}"
+  }
+
+  tools {
+    maven 'Maven-3.9.10'
+  }
+
+  stages {
+
+    stage("Checkout Code") {
+      steps {
+        git branch: 'development', credentialsId: 'GitHubCred', url: 'https://github.com/Rushi-Technologies/student-reg-webapp.git'
+      }
     }
-    
-    environment {
-        AWS_REGION = "ap-south-1"
-        EKS_CLUSTER_NAME = "eks-demo"
-        IMAGE_REGISTRY_ENDPOINT = "775694652978.dkr.ecr.ap-south-1.amazonaws.com"
-        IMAGE_REPOSITORY_NAME = "student-reg-webapp"
-        IMAGE_REGISTRY = "${IMAGE_REGISTRY_ENDPOINT}/${IMAGE_REPOSITORY_NAME}"
+
+    stage("Run Unit Tests") {
+      steps {
+        sh "mvn clean test"
+      }
     }
 
-    tools {
-        maven 'Maven-3.9.10'
+    stage("Maven Clean Package") {
+      steps {
+        sh "mvn clean package"
+      }
     }
 
-    stages {
+    stage("Build Docker Image") {
+      steps {
+        sh "docker build -t ${IMAGE_REGISTRY}:$BUILD_NUMBER ."
+      }
+    }
 
-      stage("Checkout Code"){
-           steps {
-               git branch: 'development', credentialsId: 'GitHubCred', url: 'https://github.com/Rushi-Technologies/student-reg-webapp.git'
-           }
-       }
+    stage("Push Docker Image to ECR") {
+      steps {
+        sh ""
+        "
+        aws ecr get - login - password--region ap - south - 1 | docker login--username AWS--password - stdin $ {
+          IMAGE_REGISTRY_ENDPOINT
+        }
+        docker push $ {
+          IMAGE_REGISTRY
+        }: $BUILD_NUMBER
+          ""
+        "
+      }
+    }
 
-      stage("Run Unit Tests"){
-           steps {
-               sh "mvn clean test"
-           }
-       } 
-
-
-
-      stage("Maven Clean Package"){
-           steps {
-               sh "mvn clean package"
-           }
-       }
-
-        stage("Build Docker Image"){
-             steps {
-                 sh "docker build -t ${IMAGE_REGISTRY}:$BUILD_NUMBER ."
-             }
-         }
-        
+    /**
+    stage('Update image tag in OPS repo (K8s)') {
+        steps {
+            withCredentials([usernamePassword(
+            credentialsId: 'GitHubCred',
+            usernameVariable: 'GIT_USER',
+            passwordVariable: 'GIT_TOKEN'
+            )]) {
                 
-        stage("Push Docker Image to ECR"){
-             steps {
-                     sh """
-                         aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${IMAGE_REGISTRY_ENDPOINT}
-                         docker push ${IMAGE_REGISTRY}:$BUILD_NUMBER
-                     """
-             }
-         }
-       
-        /**
-        stage('Update image tag in OPS repo (K8s)') {
-            steps {
-                withCredentials([usernamePassword(
-                credentialsId: 'GitHubCred',
-                usernameVariable: 'GIT_USER',
-                passwordVariable: 'GIT_TOKEN'
-                )]) {
-                    
-                     sh '''
-                        set -e
+                 sh '''
+                    set -e
 
-                        OPS_DIR="ops-repo"
-                        OPS_REPO="https://${GIT_USER}:${GIT_TOKEN}@github.com/Rushi-Technologies/student-reg-app-ops.git"
+                    OPS_DIR="ops-repo"
+                    OPS_REPO="https://${GIT_USER}:${GIT_TOKEN}@github.com/Rushi-Technologies/student-reg-app-ops.git"
 
-                        rm -rf "$OPS_DIR"
-                        git clone "$OPS_REPO" "$OPS_DIR"
-                    ''' 
+                    rm -rf "$OPS_DIR"
+                    git clone "$OPS_REPO" "$OPS_DIR"
+                ''' 
 
-                    dir('ops-repo') {
-                        sh '''
-                        set -e
-
-                        FILE="k8s/deployment.yaml"
-                        sed -i "s|image: \\(.*student-reg-webapp:\\).*|image: \\1${BUILD_NUMBER}|" $FILE
-
-                        git config user.email "jenkins@localhost"
-                        git config user.name "jenkins"
-
-                        if git diff --quiet; then
-                            echo "No changes detected"
-                            exit 0
-                        fi
-
-                        git add "$FILE"
-                        git commit -m "ci(helm): bump image tag to ${BUILD_NUMBER}"
-                        git push origin main
-                        '''
-                    }  
-                  
-                }
-            }
-        }
-        **/
-
-        stage('Update image tag in OPS repo (Helm)') {
-            steps {
-                withCredentials([usernamePassword(
-                credentialsId: 'GitHubCred',
-                usernameVariable: 'GIT_USER',
-                passwordVariable: 'GIT_TOKEN'
-                )]) {
-
+                dir('ops-repo') {
                     sh '''
-                        set -e
+                    set -e
 
-                        OPS_DIR="ops-repo"
-                        OPS_REPO="https://${GIT_USER}:${GIT_TOKEN}@github.com/Rushi-Technologies/student-reg-app-ops.git"
+                    FILE="k8s/deployment.yaml"
+                    sed -i "s|image: \\(.*student-reg-webapp:\\).*|image: \\1${BUILD_NUMBER}|" $FILE
 
-                        rm -rf "$OPS_DIR"
-                        git clone "$OPS_REPO" "$OPS_DIR"
-                    ''' 
+                    git config user.email "jenkins@localhost"
+                    git config user.name "jenkins"
 
-                    dir('ops-repo') {
-                        sh '''
-                        set -e
+                    if git diff --quiet; then
+                        echo "No changes detected"
+                        exit 0
+                    fi
 
-                        FILE="helm/values.yaml"
-
-                        sed -i.bak '/^[[:space:]]*image:[[:space:]]*$/,/^[^[:space:]]/ s/^[[:space:]]*tag:.*/  tag: "'"${BUILD_NUMBER}"'"/' "$FILE"
-                        rm -f "$FILE.bak"
-
-                        git config user.email "jenkins@localhost"
-                        git config user.name "jenkins"
-
-                        if git diff --quiet; then
-                            echo "No changes detected"
-                            exit 0
-                        fi
-
-                        git add "$FILE"
-                        git commit -m "ci(helm): bump image tag to ${BUILD_NUMBER}"
-                        git push origin main
-                        '''
-                    }  
-
-                }
+                    git add "$FILE"
+                    git commit -m "ci(helm): bump image tag to ${BUILD_NUMBER}"
+                    git push origin main
+                    '''
+                }  
+              
             }
         }
-       
+    }
+    **/
+
+    stage('Update image tag in OPS repo (Helm)') {
+      steps {
+        withCredentials([usernamePassword(
+          credentialsId: 'GitHubCred',
+          usernameVariable: 'GIT_USER',
+          passwordVariable: 'GIT_TOKEN'
+        )]) {
+
+          sh ''
+          '
+          set - e
+
+          OPS_DIR = "ops-repo"
+          OPS_REPO = "https://${GIT_USER}:${GIT_TOKEN}@github.com/Rushi-Technologies/student-reg-app-ops.git"
+
+          rm - rf "$OPS_DIR"
+          git clone "$OPS_REPO"
+          "$OPS_DIR"
+          ''
+          ' 
+
+          dir('ops-repo') {
+            sh ''
+            '
+            set - e
+
+            FILE = "helm/values.yaml"
+
+            sed - i.bak '/^[[:space:]]*image:[[:space:]]*$/,/^[^[:space:]]/ s/^[[:space:]]*tag:.*/  tag: "'
+            "${BUILD_NUMBER}"
+            '"/'
+            "$FILE"
+            rm - f "$FILE.bak"
+
+            git config user.email "jenkins@localhost"
+            git config user.name "jenkins"
+
+            if git diff--quiet;
+            then
+            echo "No changes detected"
+            exit 0
+            fi
+
+            git add "$FILE"
+            git commit - m "ci(helm): bump image tag to ${BUILD_NUMBER}"
+            git push origin main
+              ''
+            '
+          }
+
+        }
+      }
     }
 
-    post {
-        success {
-          echo "Build and push completed: ${IMAGE_REGISTRY}:$BUILD_NUMBER"
-        }
+  }
 
-        failure {
-          echo 'Build failed'
-        }
-        always {
-                sh 'docker system prune -f'
-                cleanWs()
-        }
+  post {
+    success {
+      echo "Build and push completed: ${IMAGE_REGISTRY}:$BUILD_NUMBER"
     }
-       
+
+    failure {
+      echo 'Build failed'
+    }
+    always {
+      sh 'docker system prune -f'
+      cleanWs()
+    }
+  }
+
 }
